### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/PotjansDiesmann2014#5]
I'm keen to add licence information to this repo. There are different versions from different sources but it would be ideal to release under a single license. @albada, @apdavison how would you feel about GPL v3? The Nest version is in their examples under GPLv2, and the PyNN version is in the main PyNN repo under CeCILL (I'm aware of a PR from @apdavison #2 which I've not had a chance to review...). Alternatively I can put separate license files in each sub repo...

**Comment by apdavison** [comment]
GPL v3 is fine with me.

**Comment by albada** [comment]
Yes, fine with me too. I'll ask the NEST developers to upgrade to GPL v3.

**Comment by pgleeson** [comment]
Thanks. Added now.
