### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/PotjansDiesmann2014#6]
Travis tests are currently failing, which is mainly down to the fact that the tests on the model have been updated and checked (locally on my machine) with NEST 2.16+, with a more recent version of PyNN, but currently the test suite (based on OMV: https://github.com/OpenSourceBrain/osb-model-validation) is using NEST 2.12. 

There is a slight change in the exact spike times between these versions, hence the failure. OMV needs to be updated to a more recent PyNN/NEST combination before these will pass. As it impacts a number of other NEST & PyNN based projects (e.g. [this](https://travis-ci.org/OpenSourceBrain/Brunel2000/builds/632330998)), it's taking some time, but will be addressed in the next week or two.

**Comment by steffengraber** [comment]
Are there any news on this?

**Comment by pgleeson** [comment]
Not yet, but I plan to be updating all relevant testing libraries next week. Note the model works as expected on recent versions of NEST, but there are just slight changes in exact spike times compared to older versions.

**Comment by pgleeson** [comment]
Have been fixed for a while...
